name: "Deploy"
on:
  push:
    branches:
      - main

permissions: 
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v11
        with:
          nix_version: 2.6.1
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: knownunown
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "(-source$|-node-dependencies-)"
      - name: nix build
        run: nix build -L .#site
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './result'

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Setup Page
        uses: actions/configure-pages@v3
      - name: Deploy Page
        uses: actions/deploy-pages@v2
